# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Enable hibernation
  boot.kernelParams = [
    "resume_offset=25608192" # swap file offset
    "mem_sleep_default=deep" # suspend first
  ];
  boot.resumeDevice = "/dev/disk/by-uuid/eef5af0e-bfa8-4609-bb14-39e5adc3f3b3";
  powerManagement.enable = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/eef5af0e-bfa8-4609-bb14-39e5adc3f3b3";
    fsType = "ext4";
    options = [
      "noatime"
      "nodiratime"
      "discard"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/9371a21a-f375-4e74-a804-14f7765f9d07";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7B90-0E1D";
    fsType = "vfat";
  };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 32 * 1024; # 32GB in MB
    }
  ];

  # Increase desktop performance
  services.tlp.settings = {
    INTEL_GPU_MIN_FREQ_ON_AC = 500;
    INTEL_GPU_MIN_FREQ_ON_BAT = 500;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Enable all firmware
  # Fix for an issue where the bluetooth is not enabled on boot
  hardware.enableAllFirmware = true;
}
